<?php

$DP = array(
						array("0","Gerät","Datenpunkt","Datenpunkttyp","Out","In","Einheit"),
						array("1","Heizgerät 1","Störung","DPT_Switch","Out","-","-"),
						array("2","Heizgerät 1","Betriebsart","DPT_HVACContrMode","Out","-","-"),
						array("3","Heizgerät 1","Modulationsgrad / Brennerleistung","DPT_Scaling","Out","-","%"),
						array("4","Heizgerät 1","Kesseltemperatur","DPT_Value_Temp","Out","-","°C"),
						array("5","Heizgerät 1","Sammlertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("6","Heizgerät 1","Rücklauftemperatur","DPT_Value_Temp","Out","-","°C"),
						array("7","Heizgerät 1","Warmwassertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("8","Heizgerät 1","Außentemperatur","DPT_Value_Temp","Out","-","°C"),
						array("9","Heizgerät 1","Status Brenner / Flamme","DPT_Switch","Out","-","-"),
						array("10","Heizgerät 1","Status Heizkreispumpe","DPT_Switch","Out","-","-"),
						array("11","Heizgerät 1","Status Speicherladepumpe","DPT_Switch","Out","-","-"),
						array("12","Heizgerät 1","Status 3-Wege-Umschaltventil","DPT_OpenClose","Out","-","-"),
						array("13","Heizgerät 1","Anlagendruck","DPT_Value_Pres","Out","-","Pa"),
						array("14","Heizgerät 2","Störung","DPT_Switch","Out","-","-"),
						array("15","Heizgerät 2","Betriebsart","DPT_HVACContrMode","Out","-","-"),
						array("16","Heizgerät 2","Modulationsgrad / Brennerleistung","DPT_Scaling","Out","-","%"),
						array("17","Heizgerät 2","Kesseltemperatur","DPT_Value_Temp","Out","-","°C"),
						array("18","Heizgerät 2","Sammlertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("19","Heizgerät 2","Rücklauftemperatur","DPT_Value_Temp","Out","-","°C"),
						array("20","Heizgerät 2","Warmwassertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("21","Heizgerät 2","Außentemperatur","DPT_Value_Temp","Out","-","°C"),
						array("22","Heizgerät 2","Status Brenner / Flamme","DPT_Switch","Out","-","-"),
						array("23","Heizgerät 2","Status Heizkreispumpe","DPT_Switch","Out","-","-"),
						array("24","Heizgerät 2","Status Speicherladepumpe","DPT_Switch","Out","-","-"),
						array("25","Heizgerät 2","Status 3-Wege-Umschaltventil","DPT_OpenClose","Out","-","-"),
						array("26","Heizgerät 2","Anlagendruck","DPT_Value_Pres","Out","-","Pa"),
						array("27","Heizgerät 3","Störung","DPT_Switch","Out","-","-"),
						array("28","Heizgerät 3","Betriebsart","DPT_HVACContrMode","Out","-","-"),
						array("29","Heizgerät 3","Modulationsgrad / Brennerleistung","DPT_Scaling","Out","-","%"),
						array("30","Heizgerät 3","Kesseltemperatur","DPT_Value_Temp","Out","-","°C"),
						array("31","Heizgerät 3","Sammlertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("32","Heizgerät 3","Rücklauftemperatur","DPT_Value_Temp","Out","-","°C"),
						array("33","Heizgerät 3","Warmwassertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("34","Heizgerät 3","Außentemperatur","DPT_Value_Temp","Out","-","°C"),
						array("35","Heizgerät 3","Status Brenner / Flamme","DPT_Switch","Out","-","-"),
						array("36","Heizgerät 3","Status Heizkreispumpe","DPT_Switch","Out","-","-"),
						array("37","Heizgerät 3","Status Speicherladepumpe","DPT_Switch","Out","-","-"),
						array("38","Heizgerät 3","Status 3-Wege-Umschaltventil","DPT_OpenClose","Out","-","-"),
						array("39","Heizgerät 3","Anlagendruck","DPT_Value_Pres","Out","-","Pa"),
						array("40","Heizgerät 4","Störung","DPT_Switch","Out","-","-"),
						array("41","Heizgerät 4","Betriebsart","DPT_HVACContrMode","Out","-","-"),
						array("42","Heizgerät 4","Modulationsgrad / Brennerleistung","DPT_Scaling","Out","-","%"),
						array("43","Heizgerät 4","Kesseltemperatur","DPT_Value_Temp","Out","-","°C"),
						array("44","Heizgerät 4","Sammlertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("45","Heizgerät 4","Rücklauftemperatur","DPT_Value_Temp","Out","-","°C"),
						array("46","Heizgerät 4","Warmwassertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("47","Heizgerät 4","Außentemperatur","DPT_Value_Temp","Out","-","°C"),
						array("48","Heizgerät 4","Status Brenner / Flamme","DPT_Switch","Out","-","-"),
						array("49","Heizgerät 4","Status Heizkreispumpe","DPT_Switch","Out","-","-"),
						array("50","Heizgerät 4","Status Speicherladepumpe","DPT_Switch","Out","-","-"),
						array("51","Heizgerät 4","Status 3-Wege-Umschaltventil","DPT_OpenClose","Out","-","-"),
						array("52","Heizgerät 4","Anlagendruck","DPT_Value_Pres","Out","-","Pa"),
						array("53","BM-2 0","Störung","DPT_Switch","Out","-","-"),
						array("54","BM-2 0","Außentemperatur","DPT_Value_Temp","Out","-","°C"),
						array("55","BM-2 0","Raumtemperatur","DPT_Value_Temp","Out","-","°C"),
						array("56","BM-2 0","Warmwassersolltemperatur","DPT_Value_Temp","Out","In","°C"),
						array("57","BM-2 0","Programmwahl Heizkreis","DPT_HVACMode","Out","In","-"),
						array("58","BM-2 0","Programmwahl Warmwasser","DPT_DHWMode","Out","In","-"),
						array("59","BM-2 0","Heizkreis Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("60","BM-2 0","Heizkreis Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("61","BM-2 0","Heizkreis Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("62","BM-2 0","Warmwasser Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("63","BM-2 0","Warmwasser Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("64","BM-2 0","Warmwasser Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("65","BM-2 0","Sollwertkorrektur","DPT_Value_Tempd_IN","Out","In","K"),
						array("66","BM-2 0","Sparfaktor","DPT_Value_Tempd","Out","In","K"),
						array("67","BM-2 1","Störung","DPT_Switch","Out","-","-"),
						array("68","BM-2 1","Raumtemperatur","DPT_Value_Temp","Out","-","°C"),
						array("69","BM-2 1","Warmwassersolltemperatur","DPT_Value_Temp","Out","In","°C"),
						array("70","BM-2 1","Programmwahl Mischer","DPT_HVACMode","Out","In","-"),
						array("71","BM-2 1","Programmwahl Warmwasser","DPT_DHWMode","Out","In","-"),
						array("72","BM-2 1","Mischer Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("73","BM-2 1","Mischer Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("74","BM-2 1","Mischer Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("75","BM-2 1","Warmwasser Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("76","BM-2 1","Warmwasser Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("77","BM-2 1","Warmwasser Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("78","BM-2 1","Sollwertkorrektur","DPT_Value_Tempd","Out","In","K"),
						array("79","BM-2 1","Sparfaktor","DPT_Value_Tempd","Out","In","K"),
						array("80","BM-2 2","Störung","DPT_Switch","Out","-","-"),
						array("81","BM-2 2","Raumtemperatur","DPT_Value_Temp","Out","-","°C"),
						array("82","BM-2 2","Warmwassersolltemperatur","DPT_Value_Temp","Out","In","°C"),
						array("83","BM-2 2","Programmwahl Mischer","DPT_HVACMode","Out","In","-"),
						array("84","BM-2 2","Programmwahl Warmwasser","DPT_DHWMode","Out","In","-"),
						array("85","BM-2 2","Mischer Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("86","BM-2 2","Mischer Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("87","BM-2 2","Mischer Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("88","BM-2 2","Warmwasser Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("89","BM-2 2","Warmwasser Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("90","BM-2 2","Warmwasser Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("91","BM-2 2","Sollwertkorrektur","DPT_Value_Tempd","Out","In","K"),
						array("92","BM-2 2","Sparfaktor","DPT_Value_Tempd","Out","In","K"),
						array("93","BM-2 3","Störung","DPT_Switch","Out","-","-"),
						array("94","BM-2 3","Raumtemperatur","DPT_Value_Temp","Out","-","°C"),
						array("95","BM-2 3","Warmwassersolltemperatur","DPT_Value_Temp","Out","In","°C"),
						array("96","BM-2 3","Programmwahl Mischer","DPT_HVACMode","Out","In","-"),
						array("97","BM-2 3","Programmwahl Warmwasser","DPT_DHWMode","Out","In","-"),
						array("98","BM-2 3","Mischer Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("99","BM-2 3","Mischer Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("100","BM-2 3","Mischer Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("101","BM-2 3","Warmwasser Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("102","BM-2 3","Warmwasser Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("103","BM-2 3","Warmwasser Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("104","BM-2 3","Sollwertkorrektur","DPT_Value_Tempd","Out","In","K"),
						array("105","BM-2 3","Sparfaktor","DPT_Value_Tempd","Out","In","K"),
						array("106","Kaskadenmodul","Störung","DPT_Switch","Out","-","-"),
						array("107","Kaskadenmodul","Sammlertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("108","Kaskadenmodul","Gesamtmodulationsgrad","DPT_Scaling","Out","-","%"),
						array("109","Kaskadenmodul","Vorlauftemperatur Mischerkreis","DPT_Value_Temp","Out","-","°C"),
						array("110","Kaskadenmodul","Status Mischerkreispumpe","DPT_Switch","Out","-","-"),
						array("111","Kaskadenmodul","Status Ausgang A1","DPT_Enable","Out","-","-"),
						array("112","Kaskadenmodul","Eingang E1","DPT_Value_Temp","Out","-","°C"),
						array("113","Kaskadenmodul","Eingang E2","DPT_Value_Temp","Out","-","°C"),
						array("114","Mischermodul 1","Störung","DPT_Switch","Out","-","-"),
						array("115","Mischermodul 1","Warmwassertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("116","Mischermodul 1","Vorlauftemperatur Mischerkreis","DPT_Value_Temp","Out","-","°C"),
						array("117","Mischermodul 1","Status Mischerkreispumpe","DPT_Switch","Out","-","-"),
						array("118","Mischermodul 1","Status Ausgang A1","DPT_Enable","Out","-","-"),
						array("119","Mischermodul 1","Eingang E1","DPT_Value_Temp","Out","-","°C"),
						array("120","Mischermodul 1","Eingang E2","DPT_Value_Temp","Out","-","°C"),
						array("121","Mischermodul 2","Störung","DPT_Switch","Out","-","-"),
						array("122","Mischermodul 2","Warmwassertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("123","Mischermodul 2","Vorlauftemperatur Mischerkreis","DPT_Value_Temp","Out","-","°C"),
						array("124","Mischermodul 2","Status Mischerkreispumpe","DPT_Switch","Out","-","-"),
						array("125","Mischermodul 2","Status Ausgang A1","DPT_Enable","Out","-","-"),
						array("126","Mischermodul 2","Eingang E1","DPT_Value_Temp","Out","-","°C"),
						array("127","Mischermodul 2","Eingang E2","DPT_Value_Temp","Out","-","°C"),
						array("128","Mischermodul 3","Störung","DPT_Switch","Out","-","-"),
						array("129","Mischermodul 3","Warmwassertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("130","Mischermodul 3","Vorlauftemperatur Mischerkreis","DPT_Value_Temp","Out","-","°C"),
						array("131","Mischermodul 3","Status Mischerkreispumpe","DPT_Switch","Out","-","-"),
						array("132","Mischermodul 3","Status Ausgang A1","DPT_Enable","Out","-","-"),
						array("133","Mischermodul 3","Eingang E1","DPT_Value_Temp","Out","-","°C"),
						array("134","Mischermodul 3","Eingang E2","DPT_Value_Temp","Out","-","°C"),
						array("135","Solarmodul","Störung","DPT_Switch","Out","-","-"),
						array("136","Solarmodul","Warmwassertemperatur Solar 1","DPT_Value_Temp","Out","-","°C"),
						array("137","Solarmodul","Temperatur Kollektor 1","DPT_Value_Temp","Out","-","°C"),
						array("138","Solarmodul","Eingang E1","DPT_Value_Temp","Out","-","°C"),
						array("139","Solarmodul","Eingang E2 (Durchfluss)","DPT_Value_Volume_Flow","Out","-","l/h"),
						array("140","Solarmodul","Eingang E3","DPT_Value_Temp","Out","-","°C"),
						array("141","Solarmodul","Status Solarkreispumpe SKP1","DPT_Switch","Out","-","-"),
						array("142","Solarmodul","Status Ausgang A1","DPT_Enable","Out","-","-"),
						array("143","Solarmodul","Status Ausgang A2","DPT_Enable","Out","-","-"),
						array("144","Solarmodul","Status Ausgang A3","DPT_Enable","Out","-","-"),
						array("145","Solarmodul","Status Ausgang A4","DPT_Enable","Out","-","-"),
						array("146","Solarmodul","Durchfluss","DPT_Value_Volume_Flow","Out","-","l/h"),
						array("147","Solarmodul","aktuelle Leistung","DPT_Power","Out","-","kW"),
						array("148","CWL Excellent","Störung","DPT_Switch","Out","-","-"),
						array("149","CWL Excellent","Programm","DPT_HVACMode","Out","In","-"),
						array("150","CWL Excellent","Zeitprogramm 1","DPT_Switch","Out","In","-"),
						array("151","CWL Excellent","Zeitprogramm 2","DPT_Switch","Out","In","-"),
						array("152","CWL Excellent","Zeitprogramm 3","DPT_Switch","Out","In","-"),
						array("153","CWL Excellent","Zeitweise Intensivlüftung AN/AUS","DPT_Switch","Out","In","-"),
						array("154","CWL Excellent","Zeitweise Intensivlüftung Startdatum","DPT_Date","Out","In","-"),
						array("155","CWL Excellent","Zeitweise Intensivlüftung Enddatum","DPT_Date","Out","In","-"),
						array("156","CWL Excellent","Zeitweise Intensivlüftung Startzeit","DPT_TimeOfDay","Out","In","-"),
						array("157","CWL Excellent","Zeitweise Intensivlüftung Endzeit","DPT_TimeOfDay","Out","In","-"),
						array("158","CWL Excellent","Zeitweiser Feuchteschutz AN/AUS","DPT_Switch","Out","In","-"),
						array("159","CWL Excellent","Zeitweiser Feuchteschutz Startdatum","DPT_Date","Out","In","-"),
						array("160","CWL Excellent","Zeitweiser Feuchteschutz Enddatum","DPT_Date","Out","In","-"),
						array("161","CWL Excellent","Zeitweiser Feuchteschutz Startzeit","DPT_TimeOfDay","Out","In","-"),
						array("162","CWL Excellent","Zeitweiser Feuchteschutz Endzeit","DPT_TimeOfDay","Out","In","-"),
						array("163","CWL Excellent","Lüftungsstufe","DPT_Scaling","Out","-","%"),
						array("164","CWL Excellent","Ablufttemperatur","DPT_Value_Temp","Out","-","°C"),
						array("165","CWL Excellent","Frischlufttemperatur","DPT_Value_Temp","Out","-","°C"),
						array("166","CWL Excellent","Luftdurchsatz Zuluft","DPT_FlowRate_m3/h","Out","-","m³/h"),
						array("167","CWL Excellent","Luftdurchsatz Abluft","DPT_FlowRate_m3/h","Out","-","m³/h"),
						array("168","CWL Excellent","Bypass Initialisierung","DPT_Bool","Out","-","-"),
						array("169","CWL Excellent","Bypass öffnet/offen","DPT_Bool","Out","-","-"),
						array("170","CWL Excellent","Bypass schließt/geschlossen","DPT_Bool","Out","-","-"),
						array("171","CWL Excellent","Bypass Fehler","DPT_Bool","Out","-","-"),
						array("172","CWL Excellent","Frost Status: Initialisierung/Warte","DPT_Bool","Out","-","-"),
						array("173","CWL Excellent","Frost Status: Kein Frost","DPT_Bool","Out","-","-"),
						array("174","CWL Excellent","Frost Status: Vorwärmer","DPT_Bool","Out","-","-"),
						array("175","CWL Excellent","Frost Status: Fehler/Unausgeglichen","DPT_Bool","Out","-","-"),
						array("176","Heizgerät 1 (BWL-1-S)","Störung","DPT_Switch","Out","-","-"),
						array("177","Heizgerät 1 (BWL-1-S)","Betriebsart","DPT_HVACContrMode","Out","-","-"),
						array("178","Heizgerät 1 (BWL-1-S)","Heizleistung","DPT_Power","Out","-","kW"),
						array("179","Heizgerät 1 (BWL-1-S)","Kühlleistung","DPT_Power","Out","-","kW"),
						array("180","Heizgerät 1 (BWL-1-S)","Kesseltemperatur","DPT_Value_Temp","Out","-","°C"),
						array("181","Heizgerät 1 (BWL-1-S)","Sammlertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("182","Heizgerät 1 (BWL-1-S)","Rücklauftemperatur","DPT_Value_Temp","Out","-","°C"),
						array("183","Heizgerät 1 (BWL-1-S)","Warmwassertemperatur","DPT_Value_Temp","Out","-","°C"),
						array("184","Heizgerät 1 (BWL-1-S)","Außentemperatur","DPT_Value_Temp","Out","-","°C"),
						array("185","Heizgerät 1 (BWL-1-S)","Status Heizkreispumpe","DPT_Switch","Out","-","-"),
						array("186","Heizgerät 1 (BWL-1-S)","Status Zubringer-/Heizkreispumpe","DPT_Switch","Out","-","-"),
						array("187","Heizgerät 1 (BWL-1-S)","Status 3-Wege-Umschaltventil HZ/WW","DPT_OpenClose","Out","-","-"),
						array("188","Heizgerät 1 (BWL-1-S)","Status 3-Wege-Umschaltventil HZ/K","DPT_OpenClose","Out","-","-"),
						array("189","Heizgerät 1 (BWL-1-S)","Status E-Heizung","DPT_Switch","Out","-","-"),
						array("190","Heizgerät 1 (BWL-1-S)","Anlagendruck","DPT_Value_Pres","Out","-","Pa"),
						array("191","Heizgerät 1 (BWL-1-S)","Leistungsaufnahme","DPT_Power","Out","-","kW"),
						array("192","CWL Excellent","Filterwarnung aktiv","DPT_Switch","Out","-","-"),
						array("193","CWL Excellent","Filterwarnung zurücksetzen","DPT_Switch","Out","In","-"),
						array("194","BM-2 0","1x Warmwasserladung","DPT_Switch","Out","In","-"),
						array("195","Solarmodul","Tagesertrag","DPT_ActiveEnergy","Out","-","Wh"),
						array("196","Solarmodul","Gesamtertrag","DPT_ActiveEnergy_kWh","Out","-","kWh"),
						array("197","Heizgerät 1","Abgastemperatur","DPT_Value_Temp","Out","-","°C"),
						array("198","Heizgerät 1","Leistungsvorgabe","DPT_Scaling","Out","In","%"),
						array("199","Heizgerät 1","Kesselsolltemperaturvorgabe","DPT_Value_Temp","Out","In","°C"),
						array("200","Heizgerät 2","Abgastemperatur","DPT_Value_Temp","Out","-","°C"),
						array("201","Heizgerät 2","Leistungsvorgabe","DPT_Scaling","Out","In","%"),
						array("202","Heizgerät 2","Kesselsolltemperaturvorgabe","DPT_Value_Temp","Out","In","°C"),
						array("203","Heizgerät 3","Abgastemperatur","DPT_Value_Temp","Out","-","°C"),
						array("204","Heizgerät 3","Leistungsvorgabe","DPT_Scaling","Out","In","%"),
						array("205","Heizgerät 3","Kesselsolltemperaturvorgabe","DPT_Value_Temp","Out","In","°C"),
						array("206","Heizgerät 4","Abgastemperatur","DPT_Value_Temp","Out","-","°C"),
						array("207","Heizgerät 4","Leistungsvorgabe","DPT_Scaling","Out","In","%"),
						array("208","Heizgerät 4","Kesselsolltemperaturvorgabe","DPT_Value_Temp","Out","In","°C"),
						array("209","Kaskadenmodul","Gesamtmodulationsgradvorgabe","DPT_Scaling","Out","In","%"),
						array("210","Kaskadenmodul","Sammlersolltemperaturvorgabe","DPT_Value_Temp","Out","In","°C"),
						array("251","BM-2 0","Erkennung verfügbare Heiz-/Mischerkreise","DPT_Value_1_Ucount","Out","-","-"),
						array("355","BM-2 0","Erkennung verfügbarer Geräte 1","DPT_Value_2_Ucount","Out","-","-"),
						array("356","BM-2 0","Erkennung verfügbarer Geräte 1","DPT_Value_2_Ucount","Out","-","-"),			
						array("357","BM-2","Unterscheidung Heizgerätetyp (HG1)","DPT_Value_1_Ucount","Out","-","-"),
						array("358","BM-2","Erkennung vorhandener Warmwasserkreise","DPT_Value_1_Ucount","Out","-","-"),
						array("359","BM-2","Unterscheidung Heizgerätetyp (HG2)","DPT_Value_1_Ucount","Out","-","-"),
						array("360","BM-2","Unterscheidung Heizgerätetyp (HG3)","DPT_Value_1_Ucount","Out","-","-"),
						array("361","BM-2","Unterscheidung Heizgerätetyp (HG4)","DPT_Value_1_Ucount","Out","-","-"),
						array("362","BM-2","Erkennung Leer","DPT_Value_2_Ucount","Out","-","-"),
						array("363","BM-2","Erkennung Leer","DPT_Value_2_Ucount","Out","-","-"),
						array("364","Heizgerät 1","Kesselsolltemperatur HG1 lesen","DPT_Value_Temp","Out","-","°C"),
						array("365","Heizgerät 2","Kesselsolltemperatur HG2 lesen","DPT_Value_Temp","Out","-","°C"),
						array("366","Heizgerät 3","Kesselsolltemperatur HG3 lesen","DPT_Value_Temp","Out","-","°C"),
						array("367","Heizgerät 4","Kesselsolltemperatur HG4 lesen","DPT_Value_Temp","Out","-","°C"),
						array("368","BM-2(0)","Vorlaufsolltemperatur dir. HK - lesen","DPT_Value_Temp","Out","-","°C"),
						array("369","BM-2(0)","Mischersolltemperatur MK1 - lesen","DPT_Value_Temp","Out","-","°C"),
						array("370","BM-2(0)","Mischersolltemperatur MK2 - lesen","DPT_Value_Temp","Out","-","°C"),
						array("371","BM-2(0)","Mischersolltemperatur MK3 - lesen","DPT_Value_Temp","Out","-","°C"),
						array("372","Allgemein","Zuletzt aktiver Störcode","DPT_Value_1_Ucount","Out","-","-")									
);
